import { Database, Place, ProductRequest, Product, User, recommendedReward, currencyForCountry } from './index';
import { asiaPlaces } from './asia-places';

export function seedDatabase(now = new Date()): Database {
  const createdAt = now.toISOString();
  const day = (n: number) => new Date(now.getTime() + n * 86400000).toISOString().slice(0, 10);
  const base = (id: string) => ({ id, createdAt });
  const users: User[] = [
    ['u-me', '소운', '소', '#E8EDDF', '가고 싶은 곳의 작은 물건을 모아요.', 0, null, 12],
    ['u-min', '민트로드', '민', '#DFEED6', '도쿄 편집숍과 캐릭터숍을 좋아해요.', 28, 100, 8],
    ['u-haru', '하루', '하', '#E6DFF6', '일정에 맞춰 꼼꼼하게 가져올게요.', 7, 100, 15],
    [
      'u-joon',
      '준의 여행',
      '준',
      '#F7E4BD',
      '사진과 영수증으로 진행 상황을 알려드려요.',
      62,
      98,
      6,
    ],
    ['u-sora', '소라', '소', '#D9EAF5', '작고 귀여운 것을 좋아해요.', 12, 100, 10],
  ].map(([id, nickname, initials, avatarColor, bio, completed, successRate, responseMinutes]) => ({
    ...base(id as string),
    nickname: nickname as string,
    initials: initials as string,
    avatarColor: avatarColor as string,
    bio: bio as string,
    completed: completed as number,
    successRate: successRate as number | null,
    responseMinutes: responseMinutes as number,
    lastActive: createdAt,
    verificationLabels: ['휴대폰', '계좌', '여행 일정'],
  }));
  const places: Place[] = [
    {
      ...base('p-shibuya'),
      name: '시부야 PARCO',
      englishName: 'SHIBUYA PARCO',
      country: 'JP',
      city: '도쿄',
      region: '시부야',
      description:
        '한 층에서 만나는 취향의 세계. 캐릭터 굿즈부터 편집숍까지, 시부야에 가는 김에 둘러봐요.',
      tags: ['캐릭터 굿즈', '편집숍', '게임·애니'],
      latitude: 35.6618,
      longitude: 139.6986,
      visitors: 18,
      requestCount: 42,
      recentTrades: 113,
      averageReward: 7800,
      theme: 'lilac',
      photo: 'tokyo',
      extraMinutes: 8,
    },
    {
      ...base('p-station'),
      name: '도쿄역 캐릭터 스트리트',
      englishName: 'TOKYO CHARACTER STREET',
      country: 'JP',
      city: '도쿄',
      region: '마루노우치',
      description:
        '기차 타기 전, 좋아하는 캐릭터를 만나는 곳. 한정 굿즈의 재고와 판매 매장은 방문 전에 확인해요.',
      tags: ['키링', '캐릭터 굿즈', '한정 상품'],
      latitude: 35.6812,
      longitude: 139.7671,
      visitors: 24,
      requestCount: 67,
      recentTrades: 96,
      averageReward: 6500,
      theme: 'butter',
      photo: 'station',
      extraMinutes: 5,
    },
    {
      ...base('p-disney'),
      name: '도쿄 디즈니씨',
      englishName: 'TOKYO DISNEYSEA',
      country: 'JP',
      city: '도쿄',
      region: '마이하마',
      description:
        '여행의 기분을 담은 작은 기념품. 입장권과 매장 접근 조건은 개별 확인이 필요해요.',
      tags: ['테마파크', '한정 굿즈'],
      latitude: 35.6267,
      longitude: 139.885,
      visitors: 11,
      requestCount: 31,
      recentTrades: 51,
      averageReward: 9000,
      theme: 'blue',
      photo: 'disney',
      extraMinutes: 30,
    },
    {
      ...base('p-osaka'),
      name: '신사이바시 캐릭터숍',
      englishName: 'SHINSAIBASHI',
      country: 'JP',
      city: '오사카',
      region: '신사이바시',
      description: '오사카 쇼핑 동선에서 찾는 작은 즐거움. 캐릭터 매장 요청을 함께 살펴보세요.',
      tags: ['캐릭터 굿즈', '잡화'],
      latitude: 34.6746,
      longitude: 135.5015,
      visitors: 16,
      requestCount: 29,
      recentTrades: 38,
      averageReward: 6200,
      theme: 'mint',
      photo: 'osaka',
      extraMinutes: 6,
    },
    {
      ...base('p-fukuoka'),
      name: '하카타역 AMU PLAZA',
      englishName: 'HAKATA AMU PLAZA',
      country: 'JP',
      city: '후쿠오카',
      region: '하카타',
      description: '기차역에서 이어지는 쇼핑. 후쿠오카 여행의 시작과 끝에서 만나요.',
      tags: ['지역 한정', '패션 잡화'],
      latitude: 33.5898,
      longitude: 130.4207,
      visitors: 9,
      requestCount: 18,
      recentTrades: 27,
      averageReward: 5800,
      theme: 'butter',
      photo: 'fukuoka',
      extraMinutes: 4,
    },
    {
      ...base('p-sapporo'),
      name: '삿포로역 스텔라 플레이스',
      englishName: 'SAPPORO STELLAR PLACE',
      country: 'JP',
      city: '삿포로',
      region: '삿포로역',
      description: '도쿄 다음 여행지까지 이어지는 일정에 삿포로의 한정 상품 부탁도 함께 담아보세요.',
      tags: ['지역 한정', '캐릭터 굿즈'],
      latitude: 43.0687,
      longitude: 141.3508,
      visitors: 7,
      requestCount: 12,
      recentTrades: 19,
      averageReward: 5100,
      theme: 'blue',
      photo: 'station',
      extraMinutes: 7,
    },
    {
      ...base('p-seongsu'),
      name: '성수 팝업 거리',
      englishName: 'SEONGSU POP-UP',
      country: 'KR',
      city: '서울',
      region: '성수',
      description:
        '이번 주말에만 만날 수 있는 취향. 실제 팝업 운영 일정과 판매처는 요청할 때 확인해요.',
      tags: ['팝업', '한정 상품'],
      latitude: 37.5445,
      longitude: 127.0557,
      visitors: 36,
      requestCount: 52,
      recentTrades: 78,
      averageReward: 4500,
      theme: 'lilac',
      photo: 'seongsu',
      extraMinutes: 3,
    },
    {
      ...base('p-jamsil'),
      name: '잠실 콘서트 MD',
      englishName: 'JAMSIL',
      country: 'KR',
      city: '서울',
      region: '잠실',
      description: '공연 보러 가는 길에 함께. 티켓 소지자만 구매 가능한 상품인지 먼저 확인해요.',
      tags: ['콘서트 MD', '공연'],
      latitude: 37.5133,
      longitude: 127.1001,
      visitors: 14,
      requestCount: 21,
      recentTrades: 19,
      averageReward: 5500,
      theme: 'blue',
      photo: 'jamsil',
      extraMinutes: 7,
    },
    {
      ...base('p-jeju'),
      name: '제주 로컬 소품숍',
      englishName: 'JEJU LOCAL',
      country: 'KR',
      city: '제주',
      region: '애월',
      description: '섬의 색과 질감을 담은 로컬 굿즈. 일상에 여행의 기억을 더해요.',
      tags: ['지역 한정', '잡화'],
      latitude: 33.462,
      longitude: 126.309,
      visitors: 8,
      requestCount: 12,
      recentTrades: 16,
      averageReward: 5000,
      theme: 'mint',
      photo: 'jeju',
      extraMinutes: 5,
    },
  ];
  places.push(...asiaPlaces(createdAt));
  const productInputs: [string, string, Product['art'], number, Product['category']][] = [
    ['p-station', '치이카와 도쿄역 한정 키링', 'keyring', 2420, 'CHARACTER'],
    ['p-shibuya', '피카츄 미니 봉제인형', 'plush', 2200, 'CHARACTER'],
    ['p-shibuya', '시부야 한정 캔버스 파우치', 'pouch', 1650, 'CHARACTER'],
    ['p-shibuya', '게임 캐릭터 핀 배지 세트', 'pin', 1200, 'GAME'],
    ['p-station', '하치와레 트래블 파우치', 'pouch', 1980, 'CHARACTER'],
    ['p-station', '도쿄 한정 아크릴 키링', 'keyring', 880, 'LOCAL'],
    ['p-disney', '리조트 한정 미니 숄더백', 'bag', 3900, 'FASHION'],
    ['p-osaka', '쿠로미 미니 키링', 'keyring', 1320, 'CHARACTER'],
    ['p-osaka', '오사카 한정 캐릭터 인형', 'plush', 2500, 'CHARACTER'],
    ['p-fukuoka', '하카타 한정 자수 파우치', 'pouch', 1800, 'LOCAL'],
    ['p-seongsu', '성수 팝업 에코백', 'bag', 22000, 'POPUP'],
    ['p-jamsil', '투어 MD 반팔 티셔츠', 'tshirt', 39000, 'CONCERT'],
    ['p-jeju', '제주 바다 자수 키링', 'keyring', 12000, 'LOCAL'],
    ['p-shibuya', '한정판 스티커·핀 패키지', 'pin', 980, 'GAME'],
    ['p-station', '몰랑 여행 미니 인형', 'plush', 1900, 'CHARACTER'],
  ];
  const products: Product[] = productInputs.map(
    ([placeId, name, art, localPrice, category], i) => ({
      ...base(`product-${i + 1}`),
      placeId,
      name,
      art,
      localPrice,
      category,
      currency: currencyForCountry(places.find((p) => p.id === placeId)!.country),
      image: '',
      url: `https://demo.moa.local/products/${i + 1}`,
    }),
  );
  const requests: ProductRequest[] = products.map((p, i) => {
    const place = places.find((x) => x.id === p.placeId)!;
    return {
      ...base(`r-${i + 1}`),
      requesterId: i === 0 ? 'u-me' : i % 2 ? 'u-sora' : 'u-haru',
      productName: p.name,
      productUrl: p.url!,
      productImage: '',
      art: p.art,
      storeName: place.name,
      placeId: place.id,
      country: place.country,
      city: place.city,
      localPrice: p.localPrice,
      currency: p.currency,
      quantity: i === 2 ? 2 : 1,
      desiredDate: day(18 + (i % 3)),
      deliveryCountry: 'KR',
      deliveryCity: '서울',
      category: p.category,
      option: '기본 옵션',
      status: i === 0 ? 'OFFER_RECEIVED' : 'REQUESTED',
      revision: 0,
      directPurchase: 'UNKNOWN',
      transport: 'DOMESTIC_PARCEL',
      deliveryAddressId: 'address-home',
      deliveryRecipient: '김소운',
      deliveryPhone: '010-1234-5678',
      deliveryPostalCode: '04524',
      deliveryAddress1: '서울 중구 세종대로 110',
      deliveryAddress2: '101동 1203호 · 예시 주소',
    };
  });
  const trips = users
    .filter((u) => ['u-me', 'u-min', 'u-haru', 'u-joon'].includes(u.id))
    .map((u, i) => ({
      ...base(`trip-${u.id}`),
      travelerId: u.id,
      departureCountry: 'KR' as const,
      departureCity: '서울',
      destinationCountry: 'JP' as const,
      destinationCity: '도쿄',
      startDate: day(4),
      endDate: day(7 + i),
      placeIds: ['p-shibuya', 'p-station'],
      maxItems: 8,
      verificationStatus: 'DEMO_VERIFIED' as const,
    }));
  const offers = users
    .filter((u) => ['u-min', 'u-haru', 'u-joon'].includes(u.id))
    .map((u, i) => ({
      ...base(`offer-${i + 1}`),
      requestId: 'r-1',
      travelerId: u.id,
      tripId: `trip-${u.id}`,
      reward: recommendedReward(requests[0]),
      estimatedPurchaseDate: day(5),
      estimatedDeliveryDate: day(13 - i),
      message: [
        '도쿄역 방문 예정이에요. 사진과 영수증도 함께 보내드릴게요.',
        '캐릭터 스트리트에 들르는 일정이에요. 꼼꼼히 확인할게요.',
        '구매 즉시 진행 상황을 알려드려요. 안전하게 포장할게요.',
      ][i],
      transport: 'DOMESTIC_PARCEL' as const,
      status: 'PENDING' as const,
    }));
  const verifications = users.flatMap((u) =>
    ['PHONE', 'ACCOUNT', 'TRIP'].map((kind, i) => ({
      ...base(`verify-${u.id}-${i}`),
      userId: u.id,
      kind: kind as 'PHONE' | 'ACCOUNT' | 'TRIP',
      status: 'DEMO_VERIFIED' as const,
      providerRef: 'demo-only',
    })),
  );
  return {
    users,
    addresses: [
      {
        ...base('address-home'),
        userId: 'u-me',
        label: '집',
        recipient: '김소운',
        phone: '010-1234-5678',
        postalCode: '04524',
        address1: '서울 중구 세종대로 110',
        address2: '101동 1203호 · 예시 주소',
        isDefault: true,
      },
    ],
    verifications,
    places,
    stores: places.map((p) => ({
      ...base(`store-${p.id}`),
      placeId: p.id,
      name: p.name,
      address: `${p.city} ${p.region} · 예시 주소`,
    })),
    trips,
    destinations: trips.flatMap((t) =>
      t.placeIds.map((p) => ({
        ...base(`${t.id}-${p}`),
        tripId: t.id,
        placeId: p,
        visitDate: t.startDate,
      })),
    ),
    products,
    requests,
    offers,
    bundles: [],
    transactions: [],
    payments: [],
    escrows: [],
    receipts: [],
    shipments: [],
    rooms: [],
    messages: [],
    reviews: [],
    notifications: [
      {
        ...base('n-welcome'),
        userId: 'u-me',
        title: '도쿄역 부탁에 여행자 3명이 손들었어요.',
        requestId: 'r-1',
        read: false,
      },
    ],
    payouts: [],
    disputes: [],
    favorites: [],
    searches: [],
    events: [],
    commands: [],
  };
}
