const brand = {
  primary: '#4F8DF7',
  primaryStrong: '#2F6FE4',
  primaryDeep: '#17366F',
  primarySoft: '#EAF2FF',
  primaryTint: '#CFE0FF',
  background: '#F8FAFD',
  surface: '#FFFFFF',
  textPrimary: '#172033',
  textSecondary: '#667085',
  textMuted: '#8D9AAF',
  border: '#E7ECF3',
  desktopBackground: '#EEF4FF',
  onPrimary: '#FFFFFF',
  overlay: '#172033CC',
  softOverlay: '#FFFFFFF2',
  shadow: '#000000',
  navySurface: '#244B84',
  navyBadge: '#2E5798',
  navyDivider: '#31558D',
  navyText: '#D3E1FA',
  navyTextSoft: '#C9D9F7',
  navyTextBright: '#EAF2FF',
  translucentWhite: '#FFFFFF24',
  warningSoft: '#FFF3D6',
  accentSoft: '#F1F5FF',
  accent: '#6B598E',
  routeSoft: '#DCEAFF',
  danger: '#D64550',
  dangerSoft: '#FFF0F2',
};

export const colors = {
  ...brand,
  // Compatibility aliases while older feature files move to semantic names.
  canvas: brand.background,
  paper: brand.surface,
  ink: brand.textPrimary,
  secondary: brand.textSecondary,
  muted: brand.textMuted,
  green: brand.primary,
  darkGreen: brand.primaryDeep,
  lime: brand.primaryTint,
  mint: brand.primarySoft,
  lilac: brand.accentSoft,
  butter: brand.warningSoft,
  blue: brand.routeSoft,
  dangerBg: brand.dangerSoft,
};
export const space = { xs: 4, sm: 8, md: 12, lg: 16, xl: 24, xxl: 32 };
export const radius = { sm: 12, md: 16, lg: 24, pill: 999 };
