const brand = {
  primary: '#0877F9',
  primaryStrong: '#0064E8',
  primaryDeep: '#0A2A56',
  primarySoft: '#EAF4FF',
  primaryTint: '#CDE5FF',
  background: '#F7FAFF',
  surface: '#FFFFFF',
  textPrimary: '#10213A',
  textSecondary: '#5E718C',
  textMuted: '#91A0B5',
  border: '#DDE8F6',
  desktopBackground: '#EDF5FF',
  onPrimary: '#FFFFFF',
  overlay: '#10213ACC',
  softOverlay: '#FFFFFFF2',
  shadow: '#0A4A9B',
  navySurface: '#0C4DA8',
  navyBadge: '#1764C5',
  navyDivider: '#2B70CA',
  navyText: '#DCEBFF',
  navyTextSoft: '#C7E0FF',
  navyTextBright: '#F2F7FF',
  translucentWhite: '#FFFFFF24',
  warningSoft: '#FFF4D8',
  accentSoft: '#EEF0FF',
  accent: '#5965D8',
  routeSoft: '#DDEEFF',
  danger: '#D63B50',
  dangerSoft: '#FFF0F3',
};

export const colors = {
  ...brand,
  // Compatibility aliases while older feature files move to semantic names.
  canvas: brand.background,
  paper: brand.surface,
  ink: brand.textPrimary,
  secondary: brand.textSecondary,
  muted: brand.textMuted,
  green: brand.primary,
  darkGreen: brand.primaryDeep,
  lime: brand.primaryTint,
  mint: brand.primarySoft,
  lilac: brand.accentSoft,
  butter: brand.warningSoft,
  blue: brand.routeSoft,
  dangerBg: brand.dangerSoft,
};
export const space = { xs: 4, sm: 8, md: 12, lg: 16, xl: 24, xxl: 32 };
export const radius = { sm: 14, md: 18, lg: 26, pill: 999 };
